#!/usr/bin/env bash
#  displays the time for 12 hours and 59 minutes

hours=-1
while [ $((++hours)) -lt 12 ]
do
	echo Hour: "$hours"
	minutes=0
	while [ $((++minutes)) -lt 60 ]
	do
		echo "$minutes"
	done
done
