#!/usr/bin/env bash
# information about school file

file="school"
if [ ! -e "$file" ]
then
	echo school does not file exists
	exit 0
fi
echo school file exists
if [ -s "$file" ]
then
	echo school file is not empty
else
	echo school file is empty
fi
if [ -f "$file" ]
then
	echo school is a regular file
fi
