#!/usr/bin/env bash
# Script for fixing nginx an running in p 8080 as user nginx
pkill apache2
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod 777 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
